version: '3.1'

networks:
  computenet:
     name: hpcnode_computenet
     external: true

services:
  ondemand001:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: ondemand001
    hostname: ondemand001.hpc.vai.org
    networks:
      computenet:
        ipv4_address: 10.152.223.250
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: 64G
