version: '3.1'

networks:
  computenet:
     name:  hpcnode_computenet
     external: true

services:
  ondemandlocal:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: ondemandlocal
    hostname: ondemandlocal.hpc.vai.org
    volumes:
      - /varidata/research/clustermgmt/vaihpc/VAIDocker/hpcOnDemand/payloads/saml/ondemandlocal_mellon:/etc/httpd/mellon:rw
    networks:
      computenet:
        ipv4_address: 10.152.223.245
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: 64G

