version: '3.1'

networks:
  computenet:
     name: hpcnode_computenet
     external: true

services:
  ondemand003:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: ondemand003
    hostname: ondemand003.hpc.vai.org
    volumes:
      - /varidata/research/clustermgmt/vaihpc/VAIDocker/hpcOnDemand/ondemand003_mellon:/etc/httpd/mellon:rw
    networks:
      computenet:
        ipv4_address: 10.152.223.246
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: 64G

