version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: eth2
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  ondemand001:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: ondemand
    hostname: ondemand.hpc.vai.org
    volumes:
      - /varidata/research/clustermgmt/vaihpc/VAIDocker/hpcOnDemand/payloads/saml/ondemand001_mellon:/etc/httpd/mellon:rw
    networks:
      computenet:
        ipv4_address: 10.152.223.250
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: 64G

