version: '3.1'

services:

  alma9:
    container_name: rstudio_alma9
    hostname: rstudio
    network_mode: bridge
    privileged: false
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    image: vanandelinstitute/alma9sshd
    volumes:
      # Authentication we use SSSD.
      - /var/run/nscd/socket:/var/run/nscd/socket
      - /etc/krb5.conf:/etc/krb5.conf
      - /etc/pam.d:/etc/pam.d
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # Authentication cannot mount individual files, because the mapping is
      # based on the inode
      - /host/data:/data

      - /primary/projects/bbc:/primary/projects/bbc:ro
      - /secondary/projects/bbc:/secondary/projects/bbc:ro
      - /primary/vari/software:/primary/vari/software/:ro
      - /cm/shared/modulefiles:/cm/shared/modulefiles:ro

    ports:
      - 22300-22400:22000-22100

    restart: always
