version: '3.1'

services:

  alma9:
    container_name: rstudio_bbc
    hostname: rstudio_bbc
    network_mode: bridge 
    privileged: false
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    environment:
      - TZ=America/Detroit
    image: 639677452477.dkr.ecr.us-east-2.amazonaws.com/rstudio:2
    volumes:
      # Authentication we use SSSD.
      #- /var/run/nscd/socket:/var/run/nscd/socket
      - /etc/krb5.conf:/etc/krb5.conf
      #- /etc/pam.d:/etc/pam.d
      #- /var/lib/sss/pipes:/var/lib/sss/pipes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # Authentication cannot mount individual files, because the mapping is
      # based on the inode
      - /home/ec2-user/studies:/data/studies
      - /home/ec2-user:/home/manageR


      # TIMEZONE
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    ports:
      - 8080:22098

    restart: always
