version: '3.1'

services:

  centos:
    container_name: centos_triche
    hostname: trichedockernode
    network_mode: bridge
    privileged: false
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    image: vaibbc/centos8_rstudio:5
    volumes:
      # Authentication we use SSSD.
      - /var/run/nscd/socket:/var/run/nscd/socket
      - /etc/krb5.conf:/etc/krb5.conf
      - /etc/pam.d:/etc/pam.d
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # Authentication cannot mount individual files, because the mapping is
      # based on the inode
      - /data/data:/data

      - /legacy/storage/projects/triche:/legacy/storage/projects/triche:ro
      - /varidata/research/projects/triche:/varidata/research/projects/triche:ro
      - /varidata/research/software:/varidata/research/software/:ro
      - /varidata/research/clustermgmt/shared-ha/modulefiles:/cm/shared/modulefiles:ro

    ports:
      - 22000-22100:22000-22100

    restart: always
