version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: eth2
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  compute001:
    container_name: compute001
    hostname: compute001
    networks: 
      computenet:
        ipv4_address: 10.152.223.1
    privileged: true
    build: ./

    volumes:
      # Authentication we use SSSD.
      - /var/run/nscd/socket:/var/run/nscd/socket
      - /etc/krb5.conf:/etc/krb5.conf
      - /etc/pam.d:/etc/pam.d
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # data
      - /varidata:/varidata:rw
      - /primary:/primary:rw
      - /secondary:/secondary:rw
      - /tmp:/var/tmp:rw
      - /varidata/research/home:/home:rw
      - /etc/hosts:/etc/hosts:ro
      - /varidata/research/clustermgmt/bright92/shared:/cm/shared:rw
      - /varidata/research/clustermgmt/shared-ha/modulefiles/bbc:/cm/shared/modulefiles/bbc:rw
      - /cm/local:/cm/local
      
    tmpfs:
      - /run
      - /run/lock
      - /tmp
   
    restart: always
