version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: ens192
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  slurm:
    extends: 
      file: compute-common-docker-compose.yml
      service: compute
    container_name: slurm
    hostname: slurm
    networks: 
      computenet:
        ipv4_address: 10.152.223.254
    environment:
      - SLURM_MASTER=slurm.hpc.vai.org
    cpus: 4.0
  mysql:
    image: mariadb:latest
    container_name: mysqlslurm
    hostname: mysqlslurm
    environment:
      MARIADB_ROOT_PASSWORD_HASH: "*097233137F449CDD6DCF0449FA11B5D189340B3B"
      MARIADB_DATABASE: slurm_acct_db
    networks: 
      computenet:
        ipv4_address: 10.152.223.253
    volumes:
      - /varidata/research/clustermgmt/vaihpc/slurm/var/lib/mysql:/var/lib/mysql 
      - /varidata/research/clustermgmt/vaihpc/slurm/etc/mysql/conf.d:/etc/mysql/conf.d 
  
