version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: eth2
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: always

  compute045:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute045
    hostname: compute045
    networks:
      computenet:
        ipv4_address: 10.152.223.45
    deploy:
      resources:
        limits:
          cpus: "40"
          memory: 200G
          pids: 256

  compute046:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute046
    hostname: compute046
    networks:
      computenet:
        ipv4_address: 10.152.223.46
    deploy:
      resources:
        limits:
          cpus: "40"
          memory: 200G
          pids: 256

  compute047:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute047
    hostname: compute047
    networks:
      computenet:
        ipv4_address: 10.152.223.47
    deploy:
      resources:
        limits:
          cpus: "40"
          memory: 200G
          pids: 256

  compute048:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute048
    hostname: compute048
    networks:
      computenet:
        ipv4_address: 10.152.223.48
    deploy:
      resources:
        limits:
          cpus: "40"
          memory: 200G
          pids: 256

