version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: eth3
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: always

  compute033:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute033
    hostname: compute033
    networks:
      computenet:
        ipv4_address: 10.152.223.33
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute034:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute034
    hostname: compute034
    networks:
      computenet:
        ipv4_address: 10.152.223.34
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute035:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute035
    hostname: compute035
    networks:
      computenet:
        ipv4_address: 10.152.223.35
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute036:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute036
    hostname: compute036
    networks:
      computenet:
        ipv4_address: 10.152.223.36
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute037:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute037
    hostname: compute037
    networks:
      computenet:
        ipv4_address: 10.152.223.37
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute038:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute038
    hostname: compute038
    networks:
      computenet:
        ipv4_address: 10.152.223.38
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute039:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute039
    hostname: compute039
    networks:
      computenet:
        ipv4_address: 10.152.223.39
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute040:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute040
    hostname: compute040
    networks:
      computenet:
        ipv4_address: 10.152.223.40
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute041:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute041
    hostname: compute041
    networks:
      computenet:
        ipv4_address: 10.152.223.41
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

  compute042:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute042
    hostname: compute042
    networks:
      computenet:
        ipv4_address: 10.152.223.42
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 26G
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 80G
          pids: 4092
    memswap_limit: 80G
    shm_size: 20G

