version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: eth2
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  compute006:
    extends: 
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute006
    hostname: compute006
    networks: 
      computenet:
        ipv4_address: 10.152.223.6
    #cpuset: "0-31"
    cpus: 128.0
