version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: always

  compute123:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute123
    hostname: compute123
    networks:
      computenet:
        ipv4_address: 10.152.223.123
    volumes:
      - /localdisk/tmp/compute123:/tmp:rw
    deploy:
      resources:
        limits:
          cpus: "28"
          memory: 384G
          pids: -1
    memswap_limit: 384G
    shm_size: 384G

