version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: eth3
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: always

  compute069:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute069
    hostname: compute069
    networks:
      computenet:
        ipv4_address: 10.152.223.69
    deploy:
      resources:
        limits:
          cpus: 64
          memory: 480G

  compute070:
    extends:
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute070
    hostname: compute070
    networks:
      computenet:
        ipv4_address: 10.152.223.70
    deploy:
      resources:
        limits:
          cpus: 64
          memory: 480G

