version: '3.1'

networks:
  computenet:
    driver: ipvlan
    driver_opts:
      parent: eth2
    ipam:
      config:
        - subnet: 10.152.222.0/23
          gateway: 10.152.222.1
          ip_range: 10.152.223.0/24

services:
  compute001:
    extends: 
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute001
    hostname: compute001
    networks: 
      computenet:
        ipv4_address: 10.152.223.1
    #cpuset: "0-31"
    cpus: 32.0

  compute002:
    extends: 
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute002
    hostname: compute002
    networks: 
      computenet:
        ipv4_address: 10.152.223.2
    #cpuset: "0-31"
    cpus: 32.0

  compute003:
    extends: 
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute003
    hostname: compute003
    networks: 
      computenet:
        ipv4_address: 10.152.223.3
    #cpuset: "0-31"
    cpus: 32.0

  compute004:
    extends: 
      file: compute-common-docker-compose.yml
      service: compute
    container_name: compute004
    hostname: compute004
    networks: 
      computenet:
        ipv4_address: 10.152.223.4
    #cpuset: "0-31"
    cpus: 32.0
