version: '3.1'

services:

  alma9:
    container_name: rstudio_alma9
    hostname: rstudio
    network_mode: bridge
    privileged: false
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    environment:
      - TZ=America/Detroit
    image: vaibbc/rstudio:R4.2
    volumes:
      # Authentication we use SSSD.
      - /var/run/nscd/socket:/var/run/nscd/socket
      - /etc/krb5.conf:/etc/krb5.conf
      - /etc/pam.d:/etc/pam.d
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # Authentication cannot mount individual files, because the mapping is
      # based on the inode
      - /data/data:/data:rw

      - /varidata/research/projects/haab:/varidata/research/projects/haab:ro
      - /varidata/research/software:/varidata/research/software/:ro
      - /varidata/research/clustermgmt/shared-ha/modulefiles:/cm/shared/modulefiles:ro

      # TIMEZONE
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro



    ports:
      - 22000-22100:22000-22100

    restart: always
